version: "3"
services:

  nginx:
    #image: nginx:1.22.1
    build: ${PWD}/_d/nginx
    ports: ["${NGINX_FWD_PORT}:80", "${NGINX_FWD_S_PORT}:443"]
    restart: always
    depends_on: [apache]
    networks: [cw4-network]
    volumes:
      - ${PWD}/_ssl:/etc/nginx/ssl
      - ${PWD}/app:/var/www/app
      - ${PWD}/_logs/nginx:/var/log/nginx/
      - ${PWD}/_d/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/_d/nginx/conf.d_default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/_d/nginx/snippets:/etc/nginx/snippets/

  varnish:
    image: varnish:6.0.11
    ports: ["${VARNISH_FWD_PORT}:80", 8443:8443]
    depends_on: [apache]
    networks: [cw4-network]
    volumes:
      - ${PWD}/_d/varnish/default.vcl:/etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_ttl=3600"

  apache:
    #image: httpd:2.4.55
    build: ${PWD}/_d/apache
    ports:
      - "${APACHE_FWD_PORT}:80"
#      - "${APACHE_FWD_S_PORT}:443"
    depends_on: [php]
    networks: [cw4-network]
    volumes:
      - ${PWD}/_ssl:/usr/local/apache2/ssl
      - ${PWD}/app:/usr/local/apache2/app
      - ${PWD}/_logs/apache:/usr/local/apache2/logs
      - ${PWD}/_d/apache/conf:/usr/local/apache2/conf

  php:
    #image: php:8.1-fpm
    build: ${PWD}/_d/php
    environment: ["XDEBUG_MODE=develop,debug"]
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on: [mysql]
    networks: [cw4-network]
    volumes:
      - ${PWD}/app:/var/www/html
      - ${PWD}/_d/php/etc:/usr/local/etc
      - ${PWD}/xdebug.log:/tmp/xdebug.log

  mysql:
    #image: mariadb:10.10.2-jammy
    build:
      context: ${PWD}/_d
      dockerfile: mariadb.Dockerfile
    restart: always
    networks: [cw4-network]
    ports: ["${MYSQL_FWD_PORT}:3306"]
    volumes:
      - dap-db2:/var/lib/mysql

volumes:
  dap-db2:

networks:
  cw4-network:
    driver: bridge



